version: '3.8'
services:
  database:
    build:
      context: ./infrastructure/database
      dockerfile: Dockerfile
    image: yousunkmybattleship_database:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - mongodb_data:/data/db

  service:
    build:
      context: .
      dockerfile: ./infrastructure/service/Dockerfile
    image: yousunkmybattleship_service:latest
    restart: "no"
    environment:
      - CONNECTION_STRING=mongodb://database:27017/game_database
    ports:
      - "8080:8080"
    depends_on:
      - database

  statistics_backend:
    build:
      context: .
      dockerfile: ./infrastructure/statistics_backend/Dockerfile
    image: yousunkmybattleship_statistics_backend:latest
    restart: "no"
    environment:
      - CONNECTION_STRING=mongodb://database:27017/game_database
    ports:
      - "8081:8081"
    depends_on:
      - database

volumes:
  mongodb_data:
    driver: local
